---
- hosts: all
  tasks:
    - win_ping:
      when: ansible_os_family=="Windows"
    - ping:
      when: ansible_os_family=="RedHat"
    - debug:
        msg: "{{ansible_nodename}} successful"
         
